### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by balbusm** [AyatanaIndicators/ayatana-indicator-messages#1]
MessagingMenu is not shown while executing python script client-example.py (available in this repo).
No error is displayed.
I noticed that below packages are generated:
    gir1.2-messagingmenu-1.0
    libmessaging-menu-dev
    libmessaging-menu0
They don't have ayatana prefix which may overlap with Ubuntu version. 
Moreover in python imports also ayatana prefix is missing.

System: Ubuntu 18.04 with GNOME desktop

**Comment by sunweaver** [comment]
This issue is indeed a problem. Originally, I planned to change the libmessaging-menu namespace to libayatana-messaging-menu namespace, but that would require many changes in 3rd party components building against libmessaging-menu.

In Debian/Ubuntu, we can do an epoch bump. But I will only start this discussion on debian-devel after the Debian buster release. Hope that is ok with everyone.

Are other distributions affected? Do other distros ship Ubuntu's version of libmessaging-menu from src:pkg indicator-messages? If not, then the epoch bump can be a viable solution.

**Comment by sunweaver** [comment]
@balbusm: just a heads up for this one. Ubuntu MATE has moved over from Ubuntu Indicators to Ayatana Indicators. They will release Ubuntu MATE 20.10 without -messages Indicator. This transition now needs to happen for the other Ubuntu flavours (and remixes), as well, at least those that use indicators.

Once, all desktops in Ubuntu have switched over to Ayatana Indicators, the -messages Ayatana System Indicator will finally be moved over from Debian to Ubuntu. I expect this to happen for the next LTS at the latest.

**Comment by bluesabre** [comment]
We just triggered a sync of xfce4-indicator-plugin from Debian, effectively dropping indicator-messages support for Xubuntu.

https://launchpad.net/ubuntu/+source/xfce4-indicator-plugin/2.4.0-1
